core/core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("fetch.urls",namespace="api_app")),
]

core/fetch/urls.py
from django.urls import path

from fetch.views import TrendView, TimelineView

app_name = "fetch"
urlpatterns = [

    path("",TrendView.as_view(),name="trend-partial"),
    path("timeline/",TimelineView.as_view(),name="timeline-partial"),
]

core/fetch/models.py
from django.db import models

# Create your models here.

core/fetch/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT

# from .tasks import my_timeline, global_trends
from .timeline import my_timeline
from .trends import global_trends



CACHE_TTL = getattr(settings,"CACHE_TTL",DEFAULT_TIMEOUT)
method_decorator(cache_page(CACHE_TTL),name="dispatch")
class TrendView(TemplateView):
    template_name = "partials/trends.html"
    
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["trendings"] = global_trends()
        print(context["trendings"] )
        return context


CACHE_TTL = getattr(settings,"CACHE_TTL",DEFAULT_TIMEOUT)
method_decorator(cache_page(CACHE_TTL),name="dispatch")
class TimelineView(TemplateView):
    """ Timeline view """

    template_name = "partials/timeline.html"
    
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["tweets"] = my_timeline()
        return context




core/core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Get global twitter trends</title>
</head>
<body>
    <div class="container" style="display: flex; justify-content:center; align-items:center; margin:30px auto;">
        <div class="wrapper">
            {% data in  results%}
            <p>{{data.name}}</p><p>{{data.url}}</p><p>{{data.tweet_volume}}</p>
            {% endfor %}
        </div>

    </div>
    
</body>
</html>

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/htmx.org@1.8.2"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Twitter dashboard</title>
</head>
<body>
    <!-- timeline tweets -->
    <nav>
        <ul>
            <li><a href="{% url 'fetch:trend-partial' %}">Gloal Trends</a></li>
            <li><a href="{% url 'fetch:timeline-partial' %}">My Timeline</a></li>
            <li>Date today: {% now "SHORT_DATETIME_FORMAT" %}</li>
        </ul>
    </nav>
    <div class="container">
        {% block timeline %}
        {% endblock timeline %}

        {% block trend %}
        {% endblock trend %}

    </div>
    
</body>
</html>

core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/htmx.org@1.8.2"></script>
    <title>Twitter dashboard</title>
</head>
<body>
    <!-- timeline tweets -->
    <div class="container" style="display: flex; justify-content:center; align-items:center; margin:30px auto;">
        <div class="wrapper" hx-get="{% url 'fetch:index-page' %}" hx-trigger="every 20s" hx-swap="innerHTML" hx-target="this">
            {% for tweet in tweets %}
            <p>{{tweet.user.name}}</p> <p>{{tweet.text}}</p>
            {% endfor %}
        </div>

    </div>
    
</body>
</html>

core/templates/partials/timeline.html
{% extend base.html %}
{% block timeline %}
    <!-- timeline tweets -->
        <div class="wrapper" hx-get="{% url 'fetch:timeline-partial' %}" hx-trigger="" hx-swap="innerHTML" hx-target="this" hx-trigger="every 600s">
            <h3>My Twitter Timeline</h3>

            {% for tweet in tweets %}
            <p> #{{forloop.counter}} | {{tweet.user.name}} {{tweet.text}}</p>
            {% endfor %}
        </div>
    {% endblock timeline %}

core/templates/partials/trends.html
{% extends "base.html" %}
<!-- global trends -->

{% block trend %}

<div class="wrapper" hx-get="{% url 'fetch:trend-partial' %}" hx-trigger="" hx-swap="innerHTML" hx-target="this" hx-trigger="every 600s">
    <h3>Twitter Global Trends</h3>

    {% for trend in trendings %}
    <p>#{{forloop.counter}}| {{trend.name}} <a href="{{trend.url}}" target="_blank">click here</a></p>
    {% endfor %}
</div>
{% endblock trend %}